api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    patch_formats:
        json: ['application/merge-patch+json']
    title:  API ANDRANA
    version: 1.0.0
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
