defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/certs/andrana/andrana.com+4.pem"
      keyFile = "/etc/certs/andrana/andrana.com+4-key.pem"

[docker]
domain = "andrana.com"
watch = true
network = "web"