resources:
  App\Entity\User:
    collectionOperations:
      api_user_login:
        method: post
        route_name: 'api_user_login'
        controller: 'App\Controller\UserController'
        openapi_context:
          summary:  Login user
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    email:
                      type: string
                      description: email of user
                    password:
                      type: string
                      description: password of user

      user_info:
        method: get
        route_name: 'user_info'
        controller: 'App\Controller\UserController'
        openapi_context:
          summary: récupérer les informations de l'utilisateur connecté


    itemOperations:
      get: ~
